FLG_TOPOCTR = 32768
FLG_SPEED = 256
FLG_SWIEPH =2
FLG_SIDEREAL = 65536
GREG_CAL= 1
JULIAN_CAL=0
AYANAMSHA_LAHIRI = 1 # # SE_SIDM_LAHIRI = 1 # https://www.astro.com/swisseph/swephprg.htm#_Toc112949017
AYANAMSHA_RAMAN = 3 # # SE_SIDM_RAMAN = 1 # https://www.astro.com/swisseph/swephprg.htm#_Toc112949017

ARIES = "Ari"
TAURUS = "Tau"
GEMINI = "Gem"
CANCER = "Can"
LEO = "Leo"
VIRGO = "Vir"
LIBRA = "Lib"
SCORPIO = "Sco"
SAGITTARIUS = "Sag"
CAPRICORN = "Cap"
AQUARIUS = "Aqu"
PISCES = "Pis"

SURYA_SYM = "☉"
CHANDRA_SYM = "☽"
MANGAL_SYM = "♂"
BUDHA_SYM = "☿"
GURU_SYM = "♃"
SHUKRA_SYM = "♀"
SHANI_SYM = "♄"
RAHU_SYM = "☊"
KETU_SYM = "☋"
URANUS_SYM = "♅"
NEPTUNE_SYM = "♆"
PLUTO_SYM = "♇"

SURYA_NAME = "SY"
CHANDRA_NAME = "CH"
MANGAL_NAME = "MA"
BUDHA_NAME = "BU"
GURU_NAME = "GU"
SHUKRA_NAME = "SK"
SHANI_NAME = "SA"
RAHU_NAME = "RA"
KETU_NAME = "KE"
URANUS_NAME = "URAN"
NEPTUNE_NAME = "NEPT"
PLUTO_NAME = "PLUT"


Zodiac_sign= {0:ARIES, 1:TAURUS, 2:GEMINI, 3:CANCER, 4:LEO, 5:VIRGO, 6:LIBRA, 7:SCORPIO, 8:SAGITTARIUS, 9:CAPRICORN, 10:AQUARIUS, 11:PISCES}
Num_To_Zodiac_sign= {ARIES:1, TAURUS:2, GEMINI:3, CANCER:4, LEO:5, VIRGO:6, LIBRA:7, SCORPIO:8, SAGITTARIUS:9, CAPRICORN:10, AQUARIUS:11, PISCES:12}

Planet_List = {0:SURYA_NAME, 1:CHANDRA_NAME, 2:BUDHA_NAME, 3:SHUKRA_NAME, 4:MANGAL_NAME, 5:GURU_NAME, 6:SHANI_NAME,7:URANUS_NAME, 8:NEPTUNE_NAME, 9:PLUTO_NAME, 10:RAHU_NAME}

House_list= [1,2,3,4,5,6,7,8,9,10,11,12]

Lord_of_rashi = { SURYA_NAME: [LEO], CHANDRA_NAME: [CANCER], BUDHA_NAME: [GEMINI, VIRGO], SHUKRA_NAME: [LIBRA, TAURUS], MANGAL_NAME: [ARIES, SCORPIO], GURU_NAME: [SAGITTARIUS, PISCES], SHANI_NAME: [CAPRICORN, AQUARIUS], RAHU_NAME: [AQUARIUS], KETU_NAME: [SCORPIO], URANUS_NAME:[AQUARIUS], NEPTUNE_NAME:[PISCES], PLUTO_NAME:[SCORPIO]}

Rashi_pandas_list = {ARIES:"rashi01", TAURUS:"rashi02", GEMINI:"rashi03", CANCER:"rashi04", LEO:"rashi05", VIRGO:"rashi06", LIBRA:"rashi07", SCORPIO:"rashi08", SAGITTARIUS:"rashi09", CAPRICORN:"rashi10", AQUARIUS:"rashi11", PISCES:"rashi12"}

# Lord_of_rashi = {
#    "SU": ["Leo"],
#    "MO": ["Can"],
#    "ME": ["Gem", "Vir"],
#    "VE": ["Lib", "Tau"],
#    "MA": ["Ari", "Sco"],
#    "JU": ["Sag", "Pis"],
#    "SA": ["Cap", "Aqu"],
#    "RA": ["Aqu"],
#    "KE": ["Sco"],
# }
